"function onReportLocationSetLocationFalse(targetClassMethod) {\n"
"var delim = targetClassMethod.lastIndexOf(\".\");\n"
"if (delim === -1) return;\n"
"var targetClass = targetClassMethod.slice(0, delim)\n"
"var targetMethod = targetClassMethod.slice(delim + 1, targetClassMethod.length)\n"
"var hook = Java.use(targetClass);\n"
"var overloadCount = hook[targetMethod].overloads.length;\n"
"for (var i = 0; i < overloadCount; i++) {\n"
"hook[targetMethod].overloads[i].implementation = function() {\n"
"if(arguments[0] !== null) {\n"
"arguments[0].setIsFromMockProvider(false);\n"
"}\n"
"this[targetMethod].apply(this, arguments);\n"
"return;\n"
"}\n"
"}\n"
"}\n"
"\n"
"function isMockSetLocationMockFalse(targetClassMethod) {\n"
"var delim = targetClassMethod.lastIndexOf(\".\");\n"
"if (delim === -1) return;\n"
"var targetClass = targetClassMethod.slice(0, delim)\n"
"var targetMethod = targetClassMethod.slice(delim + 1, targetClassMethod.length)\n"
"var hook = Java.use(targetClass);\n"
"var overloadCount = hook[targetMethod].overloads.length;\n"
"for (var i = 0; i < overloadCount; i++) {\n"
"hook[targetMethod].overloads[i].implementation = function() {\n"
"if(arguments[0] !== null) {\n"
"arguments[0].setIsFromMockProvider(false);\n"
"}\n"
"this[targetMethod].apply(this, arguments);\n"
"return;\n"
"}\n"
"}\n"
"}\n"
"\n"
"function setLocationResultMockFalse(targetClassMethod) {\n"
"var delim = targetClassMethod.lastIndexOf(\".\");\n"
"if (delim === -1) return;\n"
"var targetClass = targetClassMethod.slice(0, delim)\n"
"var targetMethod = targetClassMethod.slice(delim + 1, targetClassMethod.length)\n"
"var hook = Java.use(targetClass);\n"
"var overloadCount = hook[targetMethod].overloads.length;\n"
"for (var i = 0; i < overloadCount; i++) {\n"
"hook[targetMethod].overloads[i].implementation = function() {\n"
"if(arguments[0] !== null) {\n"
"arguments[0].setIsFromMockProvider(false);\n"
"}\n"
"this[targetMethod].apply(this, arguments);\n"
"return;\n"
"}\n"
"}\n"
"}\n"
"\n"
"function setLocationResultMockFalseAndroidNew(targetClassMethod) {\n"
"var delim = targetClassMethod.lastIndexOf(\".\");\n"
"if (delim === -1) return;\n"
"var targetClass = targetClassMethod.slice(0, delim)\n"
"var targetMethod = targetClassMethod.slice(delim + 1, targetClassMethod.length)\n"
"var hook = Java.use(targetClass);\n"
"var overloadCount = hook[targetMethod].overloads.length;\n"
"for (var i = 0; i < overloadCount; i++) {\n"
"hook[targetMethod].overloads[i].implementation = function() {\n"
"if(arguments[0] !== null) {\n"
"arguments[0].setMock(false);\n"
"}\n"
"this[targetMethod].apply(this, arguments);\n"
"return;\n"
"}\n"
"}\n"
"}\n"
"\n"
"function overwriteReturnFalse(targetClassMethod) {\n"
"var delim = targetClassMethod.lastIndexOf(\".\");\n"
"if (delim === -1) return;\n"
"var targetClass = targetClassMethod.slice(0, delim)\n"
"var targetMethod = targetClassMethod.slice(delim + 1, targetClassMethod.length)\n"
"var hook = Java.use(targetClass);\n"
"var overloadCount = hook[targetMethod].overloads.length;\n"
"for (var i = 0; i < overloadCount; i++) {\n"
"hook[targetMethod].overloads[i].implementation = function() {\n"
"return false;\n"
"}\n"
"}\n"
"}\n"
"\n"
"setTimeout(function() {\n"
"if(Java.available) {\n"
"Java.perform(function() {\n"
"var ver = Java.use('android.os.Build$VERSION');\n"
"var sdk = ver.SDK_INT.value;\n"
"if (sdk >= 31) {\n"
"setLocationResultMockFalseAndroidNew(\"com.android.server.location.provider.LocationProviderManager.setLastLocation\");\n"
"overwriteReturnFalse(\"android.location.Location.isMock\");\n"
"setLocationResultMockFalseAndroidNew(\"com.android.server.location.provider.LocationProviderManager.injectLastLocation\");\n"
"} else if (sdk > 29) {\n"
"onReportLocationSetLocationFalse(\"com.android.server.location.LocationManagerService$LocationProviderManager.onReportLocation\");\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.handleLocationChangedLocked\");\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.handleLocationChanged\");\n"
"} else if (sdk == 29) {\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService$LocationProvider.onReportLocation\");\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.handleLocationChangedLocked\");\n"
"} else {\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.reportLocation\");\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.handleLocationChanged\");\n"
"onReportLocationSetLocationFalse(\"com.android.server.LocationManagerService.handleLocationChangedLocked\");\n"
"}\n"
"});\n"
"}\n"
"}, 0);\n"
